services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve_scanner_backend
    privileged: true
    dns:
      - 8.8.8.8

    volumes:
      - ./scanner_backend/output:/app/output

      # ⭐ Reportes Nuclei → carpeta local
      - ./scanner_backend/nuclei_output:/app/nuclei_output

      # ⭐ Historial Nuclei → archivo local
      - ./scanner_backend/nuclei_output/nuclei_history.json:/app/nuclei_history.json

      - /proc:/proc
      - /sys:/sys
      - /dev:/dev

    ports:
      - "9000:9100"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - cve_net

  frontend:
    build:
      context: ./scanner_frontend
      dockerfile: Dockerfile
    container_name: cve_scanner_frontend
    ports:
      - "5173:5173"
    networks:
      - cve_net

networks:
  cve_net:
    driver: bridge

