services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve_scanner_backend
    privileged: true
    volumes:
      - ./scanner_backend/output:/app/output
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cve_net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve_scanner_server
    privileged: true
    volumes:
      - ./scanner_backend/output:/app/output
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
    networks:
      - cve_net

  frontend:
    build:
      context: ./scanner_frontend
      dockerfile: Dockerfile
    container_name: cve_scanner_frontend
    ports:
      - "5173:5173"
    networks:
      - cve_net

networks:
  cve_net:

