services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cve_scanner
    ports:
      - "5000:5000"
      - "9000:9000"
    volumes:
      - ./scanner_backend/output:/app/output
    networks:
      - internal_net

  frontend:
    build:
      context: ./scanner_frontend
      dockerfile: Dockerfile
    container_name: cve_frontend
    ports:
      - "5173:5173"
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

